### ISSUE TITLE
Error in kruskal.pretty

### ISSUE THREAD

**Issue by tbmonica84** [asteinberger9/seq_scripts#2]
Hi @asteinberger9 , thank you so much for the seq_scripts repo. I successfully ran simper.pretty and now I'd like to use kruskal.pretty. However, I keep getting this error message:
 Error in`[<-.data.frame`(`*tmp*`, , 6, value = numeric(0)) : new columns would leave holes after existing columns
Could you please help me to fix it?
Thank you!

**Comment by jarrodscott** [comment]
hi @tbmonica84 Did you ever solve this issue?

**Comment by antoine4ucsd** [comment]
same error. anyone can help with that?
my simper.results file looks ok with simper.pretty 
``
simper.pretty(OTU, meta, c("pid"), perc_cutoff=1, low_cutoff = 'y', low_val=0.001, "tryme")
``

but then I got:

``
simper.results = data.frame(read.csv("tryme_clean_simper.csv"))
kruskal.pretty(OTU, meta, simper.results, c("pid"), "output_name_krustal")
Error in `[<-.data.frame`(`*tmp*`, , 6, value = numeric(0)) : 
  new columns would leave holes after existing columns
Called from: `[<-.data.frame`(`*tmp*`, , 6, value = numeric(0))
``
I am attaching the simper.results if it helps.... 
[tryme_clean_simper.txt](https://github.com/asteinberger9/seq_scripts/files/5453734/tryme_clean_simper.txt)


thank you in advance!

**Comment by maryfraou** [comment]
Hello everyone!

Thank you @asteinberger9 for sharing the seq_scripts and @kdillmcfarland for the micro_ecol scripts for amplicon microbiota data analysis.

I get the same error with kruskal_pretty function:
Error in `[<-.data.frame`(`*tmp*`, , 11, value = NULL) : 
  new columns would leave holes after existing columns.

Has anyone managed to resolve that issue or have an idea of what that implies?

Cheers

**Comment by asteinberger9** [comment]
Hi all, apologies for those who did not email me directly for help. I just pushed an updated version of the script which should fix the [<-.data.frame(*tmp*   error. Also check out the README.md for updated info on input formatting and some troubleshooting options. 

Let me know if you run into any additional issues.

Best!

**Comment by AbidHussainBhat** [comment]
@asteinberger9 @jarrodscott @antoine4ucsd @tbmonica84 @maryfraouI am getting this error while running kruskal.pretty: 
kruskal.pretty(OTU.clean, meta, simper.results, c('Group'), 'Group', tax) Error in eval(predvars, data, env) : object 'listbact' not found
Can you please solve this issue?
