### ISSUE TITLE
Error simper.pretty function (subscript) logical subscript too long 

### ISSUE THREAD

**Issue by NitoCR** [asteinberger9/seq_scripts#4]
Hi, first of all thanks for the scripts.
I need the script to see the actual dissimiliarity %contribution value of each species in my research.
I have problem with simper.pretty as shown below

source("D:/Afry/R/seq_scripts-1.1/seq_scripts-1.1/simper_pretty.R")
Error in comm[group == comp[i, 1], , drop = FALSE] :
(subscript) logical subscript too long

where can i get your email so i can give you my data set i use?

**Comment by asteinberger9** [comment]
Hi @NitoCR,
I am glad the scripts will be helpful for you and apologies they are giving you errors.
Based on the error you received I think the issue may be with your data format. That is the most common cause of failure with these scripts. If you have not already done so, please visit the readme for these scripts, specifically the section "Examples of Recommended Input Formats" and make sure your data are formatted as required. Hopefully this will resolve those errors.
